image: gitlab/dind:latest

services:
- docker:dind

stages:
- build
- deploy

variables:
  CONTAINER_RELEASE_IMAGE: gitlab.madisonhub.org:4567/trbinfra/double-jeopardy:$CI_BUILD_REF_NAME

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.madisonhub.org:4567
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
